### ISSUE TITLE
Please tell me how to mine this coin? Is there a pool somewhere?

### ISSUE THREAD

**Issue by githubbelgorod** [tradecraftio/tradecraft#101]

**Comment by maaku** [comment]
Hi! Thank you for your interest.

Freicoin/Tradecraft is merge-mined with bitcoin, so you need a bitcoin miner to be able to mine this coin. We have a unique merge-mining implementation which is different from any other coin. You can read about it here:

https://github.com/tradecraftio/tradecraft/blob/18/doc/auxpow.md

There is one official pool setup which you can use to mine both bitcoin and freicoin simultaneously. Just point your bitcoin ASIC miner at one of the following pools:

```
us-west-2.aws.pool.tradecraft.io:9332
eu-west-1.aws.pool.tradecraft.io:9332
ap-northeast-1.aws.pool.tradecraft.io:9332
```

Use your bitcoin address as your username. As the password, use `freicoin=FREICOIN_ADDRESS` where you replace `FREICOIN_ADDRESS` with your own freicoin address, of course. You will be simultaneously mining both bitcoin and freicoin.

**Comment by githubbelgorod** [comment]
Thank you! )
